# nom du workflow
name: Premier workflow

# on précise quel est le déclencheur de notre workflow
on: workflow_dispatch

jobs:
    # definition de la 1ere action a realiser
    premier-job :
        # on précise le systeme d'exploitation (runner)
        runs-on: ubuntu-latest

        # on ecrit ici les etapes de notre action
        steps:
            - name: Dit bonjour
              run: echo "Hello World !!"

            - name: Dit bye
              run: echo "SALUT MEC"
              
    second-job:
        runs-on: ubuntu-latest
        steps:
                - name: etape
                  run: echo "ICH BIN EIN ZECOND JOB"